name: Dynamic Secrets Access

on:
    workflow_call:
        inputs:
            SECRETS_LIST:
                description: 'Comma-separated list of secret names to retrieve (e.g. "AZURE_CREDENTIALS,SECRET")'
                required: true
                type: string
        secrets:
            AZURE_CREDENTIALS:
                required: false
            SECRET:
                required: false

jobs:
    retrieve-secrets:
        environment: dev
        runs-on: ubuntu-latest

        steps:
            - name: Check out
              uses: actions/checkout@v4

            - name: Retrieve secrets
              run: |
                  # Convert comma-separated list to array
                  IFS=',' read -ra SECRET_NAMES <<< "${{ inputs.SECRETS_LIST }}"

                  # Create a JSON file to store all secrets
                  echo "{" > secrets-output.json

                  # Process each secret
                  for secret_name in "${SECRET_NAMES[@]}"; do
                    # Remove any whitespace
                    secret_name=$(echo "$secret_name" | tr -d ' ')

                    # Dynamically retrieve the secret
                    secret_value="${{ secrets[format('{0}', secret_name)] }}"

                    # Add to JSON (with comma for all but last item)
                    if [ "${secret_name}" != "${SECRET_NAMES[-1]}" ]; then
                      echo "  \"${secret_name}\": \"${secret_value}\"," >> secrets-output.json
                    else
                      echo "  \"${secret_name}\": \"${secret_value}\"" >> secrets-output.json
                    fi

                    echo "Processed secret: ${secret_name}"
                  done

                  echo "}" >> secrets-output.json

            - name: Upload secrets artifact
              uses: actions/upload-artifact@v4
              with:
                  name: processed-secrets
                  path: secrets-output.json
                  if-no-files-found: error
