name: Dynamic Secrets Access

on:
    workflow_call:
        inputs:
            SECRETS_LIST:
                description: 'Comma-separated list of secret names to retrieve (e.g. "AZURE_CREDENTIALS,SECRET")'
                required: true
                type: string
        secrets:
            AZURE_CREDENTIALS:
                required: false
            SECRET:
                required: false

jobs:
    retrieve-secrets:
        environment: dev
        runs-on: ubuntu-latest
        env:
            SECRET_TEST: ${{ secrets.SECRET }}

        steps:
            -   name: Check out
                uses: actions/checkout@v4

            -   name: setup python
                uses: actions/setup-python@v5
                with:
                    python-version: 3.12

            -   name: Retrieve secrets
                run: |
                    echo "Test secrets ${{ inputs.SECRETS_LIST }}"
                    # Convert comma-separated list to array
                    IFS=',' read -ra SECRET_NAMES <<< "${{ inputs.SECRETS_LIST }}"

                    # Create a JSON file to store all secrets
                    echo "{" > secrets-output.json



                    echo "}" >> secrets-output.json

            -   name: Run Script
                run: python3 .github/workflows/keys.py

            -   name: Upload secrets artifact
                uses: actions/upload-artifact@v4
                with:
                    name: processed-secrets
                    path: secrets-output.json
                    if-no-files-found: error
