
name: Dynamic Secrets Access

on:
    workflow_call:
        inputs:
            SECRET_NAME:
                description: 'Name of the secret to retrieve'
                required: true
                type: string
        secrets:
            AZURE_CREDENTIALS:
                required: false
            SECRET:
                required: false

jobs:
    retrieve-secrets:
        environment: dev
        runs-on: ubuntu-latest

        steps:
            - name: Check out
              uses: actions/checkout@v4

            - name: Retrieve secret
              env:
                  SECRET_NAME: ${{ inputs.SECRET_NAME }}
              run: |
                  secret_value="${{ secrets[inputs.SECRET_NAME] }}"
                  echo "The secret value for ${SECRET_NAME} is $secret_value"

                  # Write to file if needed
                  echo "${SECRET_NAME}='$secret_value'" >> ${SECRET_NAME}-secret.json

            - name: Upload secret artifact
              uses: actions/upload-artifact@v4
              with:
                  name: secret-${{ inputs.SECRET_NAME }}
                  path: ${{ inputs.SECRET_NAME }}-secret.json
                  if-no-files-found: ignore
